//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flaherty.Services.GoogleCharts.WebControls.SampleApp {
    
    
    public partial class Default {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// PieChart1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Flaherty.Services.GoogleCharts.WebControls.PieChart PieChart1;
        
        /// <summary>
        /// PieChart2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Flaherty.Services.GoogleCharts.WebControls.PieChart PieChart2;
        
        /// <summary>
        /// PieChart3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Flaherty.Services.GoogleCharts.WebControls.PieChart PieChart3;
        
        /// <summary>
        /// PieChart4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Flaherty.Services.GoogleCharts.WebControls.PieChart PieChart4;
        
        /// <summary>
        /// PieChart5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Flaherty.Services.GoogleCharts.WebControls.PieChart PieChart5;
        
        /// <summary>
        /// PieChart6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Flaherty.Services.GoogleCharts.WebControls.PieChart PieChart6;
    }
}
